var myData = [ {
    "id": 1,
    "squareFootage": 529,
    "pricePerSquareFoot": 1277,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Krajan Satu",
    "streetAddress": "9 Cottonwood Crossing",
    "stars": 30,
    "realty": "Quigley, Cole and Oberbrunner",
    "shortRealtor": 'placeholder', 
    "realtor": "Baldwin Delafont"
  }, {
    "id": 2,
    "squareFootage": 467,
    "pricePerSquareFoot": 1243,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "La Cruz",
    "streetAddress": "48 Petterle Park",
    "stars": 26,
    "realty": "Gottlieb-Bruen",
    "shortRealtor": 'placeholder',
    "realtor": "Bartie Bryant"
  }, {
    "id": 3,
    "squareFootage": 598,
    "pricePerSquareFoot": 1286,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Korostyshiv",
    "streetAddress": "4504 South Street",
    "stars": 34,
    "realty": "Boyle-Waters",
    "shortRealtor": 'placeholder',
    "realtor": "Dirk Bramsom"
  }, {
    "id": 4,
    "squareFootage": 506,
    "pricePerSquareFoot": 1177,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Berthierville",
    "streetAddress": "37 Tony Pass",
    "stars": 50,
    "realty": "Gottlieb-Corkery",
    "shortRealtor": 'placeholder',
    "realtor": "Joice Wolters"
  }, {
    "id": 5,
    "squareFootage": 504,
    "pricePerSquareFoot": 1134,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Trelew",
    "streetAddress": "5 Hazelcrest Alley",
    "stars": 33,
    "realty": "Lind LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Mehetabel Andriss"
  }, {
    "id": 6,
    "squareFootage": 567,
    "pricePerSquareFoot": 906,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Nioro",
    "streetAddress": "2248 Merrick Terrace",
    "stars": 36,
    "realty": "Rippin-Grady",
    "shortRealtor": 'placeholder',
    "realtor": "Auberta Le Grove"
  }, {
    "id": 7,
    "squareFootage": 423,
    "pricePerSquareFoot": 866,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Mrs",
    "neighborhood": "Migues",
    "streetAddress": "52 Sage Alley",
    "stars": 38,
    "realty": "Tillman-Schneider",
    "shortRealtor": 'placeholder',
    "realtor": "Rinaldo Trappe"
  }, {
    "id": 8,
    "squareFootage": 456,
    "pricePerSquareFoot": 1107,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Mr",
    "neighborhood": "Bobonan",
    "streetAddress": "081 Johnson Street",
    "stars": 24,
    "realty": "Rosenbaum, Grimes and Powlowski",
    "shortRealtor": 'placeholder',
    "realtor": "Ardene Phizackarley"
  }, {
    "id": 9,
    "squareFootage": 444,
    "pricePerSquareFoot": 1081,
    "rooms": 3,
    "beds": 1,
    "baths": 1,
    "houseType": "Mrs",
    "neighborhood": "Skotoússa",
    "streetAddress": "74 Dwight Center",
    "stars": 36,
    "realty": "Weber-Stokes",
    "shortRealtor": 'placeholder',
    "realtor": "Scarlett Sainz"
  }, {
    "id": 10,
    "squareFootage": 567,
    "pricePerSquareFoot": 828,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Leworook",
    "streetAddress": "87198 Duke Crossing",
    "stars": 12,
    "realty": "Harvey LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Kalle Olenchenko"
  }, {
    "id": 11,
    "squareFootage": 546,
    "pricePerSquareFoot": 1188,
    "rooms": 3,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Leipzig",
    "streetAddress": "9818 Forest Run Pass",
    "stars": 26,
    "realty": "Robel-Kulas",
    "shortRealtor": 'placeholder',
    "realtor": "Minna Tolle"
  }, {
    "id": 12,
    "squareFootage": 496,
    "pricePerSquareFoot": 1154,
    "rooms": 3,
    "beds": 1,
    "baths": 1,
    "houseType": "Mr",
    "neighborhood": "Burgersdorp",
    "streetAddress": "9035 Jenna Park",
    "stars": 15,
    "realty": "Flatley Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Tilly Belvard"
  }, {
    "id": 13,
    "squareFootage": 499,
    "pricePerSquareFoot": 1273,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Kuchurhan",
    "streetAddress": "82528 Magdeline Circle",
    "stars": 40,
    "realty": "Bode Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Ward Spawell"
  }, {
    "id": 14,
    "squareFootage": 494,
    "pricePerSquareFoot": 845,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Drosáto",
    "streetAddress": "476 Hovde Alley",
    "stars": 18,
    "realty": "Kunze, Nienow and Kilback",
    "shortRealtor": 'placeholder',
    "realtor": "Chelsey McKern"
  }, {
    "id": 15,
    "squareFootage": 588,
    "pricePerSquareFoot": 1093,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Vrýses",
    "streetAddress": "850 Clarendon Circle",
    "stars": 35,
    "realty": "Homenick LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Maddy Maxted"
  }, {
    "id": 16,
    "squareFootage": 487,
    "pricePerSquareFoot": 1040,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Vršac",
    "streetAddress": "68955 Troy Pass",
    "stars": 44,
    "realty": "Boyle Group",
    "shortRealtor": 'placeholder',
    "realtor": "Sandra Glazer"
  }, {
    "id": 17,
    "squareFootage": 486,
    "pricePerSquareFoot": 964,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Sinajana Village",
    "streetAddress": "902 Sundown Drive",
    "stars": 43,
    "realty": "Mosciski, Reinger and Lowe",
    "shortRealtor": 'placeholder',
    "realtor": "Lacey Witham"
  }, {
    "id": 18,
    "squareFootage": 535,
    "pricePerSquareFoot": 1003,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Xiaping",
    "streetAddress": "9 South Circle",
    "stars": 4,
    "realty": "Koepp Group",
    "shortRealtor": 'placeholder',
    "realtor": "Bibbye Foley"
  }, {
    "id": 19,
    "squareFootage": 534,
    "pricePerSquareFoot": 1054,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Mr",
    "neighborhood": "Kiten",
    "streetAddress": "084 Bartelt Court",
    "stars": 21,
    "realty": "Mraz LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Carrissa Hrinishin"
  }, {
    "id": 20,
    "squareFootage": 470,
    "pricePerSquareFoot": 1256,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Dmanisi",
    "streetAddress": "15948 Drewry Way",
    "stars": 13,
    "realty": "Waelchi-Bailey",
    "shortRealtor": 'placeholder',
    "realtor": "Jeremias Brunke"
  }, {
    "id": 21,
    "squareFootage": 577,
    "pricePerSquareFoot": 1087,
    "rooms": 3,
    "beds": 1,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Włocławek",
    "streetAddress": "3 Continental Crossing",
    "stars": 15,
    "realty": "White, Pfeffer and Bartoletti",
    "shortRealtor": 'placeholder',
    "realtor": "Dorothee Izkovitch"
  }, {
    "id": 22,
    "squareFootage": 427,
    "pricePerSquareFoot": 1011,
    "rooms": 1,
    "beds": 1,
    "baths": 1,
    "houseType": "Mr",
    "neighborhood": "Caminaca",
    "streetAddress": "89 Hovde Circle",
    "stars": 28,
    "realty": "Paucek, Conroy and Lindgren",
    "shortRealtor": 'placeholder',
    "realtor": "Cristabel Wittman"
  }, {
    "id": 23,
    "squareFootage": 581,
    "pricePerSquareFoot": 1097,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Kabuynan",
    "streetAddress": "52047 Lotheville Point",
    "stars": 16,
    "realty": "Koch-Carroll",
    "shortRealtor": 'placeholder',
    "realtor": "Teena Keeble"
  }, {
    "id": 24,
    "squareFootage": 521,
    "pricePerSquareFoot": 1091,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Peixing",
    "streetAddress": "16639 Macpherson Circle",
    "stars": 25,
    "realty": "Goldner Group",
    "shortRealtor": 'placeholder',
    "realtor": "Harriott Philipsson"
  }, {
    "id": 25,
    "squareFootage": 1002,
    "pricePerSquareFoot": 1281,
    "rooms": 6,
    "beds": 2,
    "baths": 2,
    "houseType": "Dr",
    "neighborhood": "Wucun",
    "streetAddress": "93700 Northfield Parkway",
    "stars": 6,
    "realty": "Friesen LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Dallas O'Curneen"
  }, {
    "id": 26,
    "squareFootage": 870,
    "pricePerSquareFoot": 930,
    "rooms": 2,
    "beds": 2,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Capiíbary",
    "streetAddress": "59 Homewood Terrace",
    "stars": 15,
    "realty": "Kautzer Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Jordan Bailess"
  }, {
    "id": 27,
    "squareFootage": 995,
    "pricePerSquareFoot": 895,
    "rooms": 2,
    "beds": 2,
    "baths": 2,
    "houseType": "Mrs",
    "neighborhood": "Dananshan",
    "streetAddress": "7 Quincy Lane",
    "stars": 11,
    "realty": "Boyle, Ziemann and Bernier",
    "shortRealtor": 'placeholder',
    "realtor": "Trenna McCloughlin"
  }, {
    "id": 28,
    "squareFootage": 1384,
    "pricePerSquareFoot": 882,
    "rooms": 5,
    "beds": 1,
    "baths": 2,
    "houseType": "Honorable",
    "neighborhood": "Masaran",
    "streetAddress": "7486 Main Park",
    "stars": 33,
    "realty": "Ullrich-Sawayn",
    "shortRealtor": 'placeholder',
    "realtor": "Mikey Fricker"
  }, {
    "id": 29,
    "squareFootage": 1048,
    "pricePerSquareFoot": 1355,
    "rooms": 4,
    "beds": 1,
    "baths": 1,
    "houseType": "Ms",
    "neighborhood": "Susapaya",
    "streetAddress": "05 Sugar Point",
    "stars": 47,
    "realty": "Bashirian, Bruen and Wilkinson",
    "shortRealtor": 'placeholder',
    "realtor": "Mariya Phelipeaux"
  }, {
    "id": 30,
    "squareFootage": 1431,
    "pricePerSquareFoot": 1300,
    "rooms": 6,
    "beds": 1,
    "baths": 2,
    "houseType": "Mr",
    "neighborhood": "San Salvador",
    "streetAddress": "6597 Maple Court",
    "stars": 36,
    "realty": "Rosenbaum, Windler and Glover",
    "shortRealtor": 'placeholder',
    "realtor": "Arnie Dallinder"
  }, {
    "id": 31,
    "squareFootage": 844,
    "pricePerSquareFoot": 1107,
    "rooms": 5,
    "beds": 2,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Abuyog",
    "streetAddress": "8 Bunting Junction",
    "stars": 47,
    "realty": "Luettgen, Ritchie and Bins",
    "shortRealtor": 'placeholder',
    "realtor": "Paxton Wilkison"
  }, {
    "id": 32,
    "squareFootage": 658,
    "pricePerSquareFoot": 1058,
    "rooms": 6,
    "beds": 2,
    "baths": 2,
    "houseType": "Mr",
    "neighborhood": "Jielong",
    "streetAddress": "2 Daystar Court",
    "stars": 28,
    "realty": "Corwin Group",
    "shortRealtor": 'placeholder',
    "realtor": "Trudey Peres"
  }, {
    "id": 33,
    "squareFootage": 1499,
    "pricePerSquareFoot": 1326,
    "rooms": 6,
    "beds": 1,
    "baths": 2,
    "houseType": "Mrs",
    "neighborhood": "Dziadkowice",
    "streetAddress": "7235 Forster Junction",
    "stars": 20,
    "realty": "Wisoky-Gottlieb",
    "shortRealtor": 'placeholder',
    "realtor": "Louella Sherborne"
  }, {
    "id": 34,
    "squareFootage": 886,
    "pricePerSquareFoot": 1330,
    "rooms": 3,
    "beds": 1,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Castle Bruce",
    "streetAddress": "3 Veith Plaza",
    "stars": 1,
    "realty": "Kovacek LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Maggee Langshaw"
  }, {
    "id": 35,
    "squareFootage": 991,
    "pricePerSquareFoot": 1093,
    "rooms": 4,
    "beds": 2,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Muldersdriseloop",
    "streetAddress": "0309 Dovetail Avenue",
    "stars": 49,
    "realty": "Harber LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Shannen Gueinn"
  }, {
    "id": 36,
    "squareFootage": 1070,
    "pricePerSquareFoot": 1166,
    "rooms": 3,
    "beds": 2,
    "baths": 2,
    "houseType": "Ms",
    "neighborhood": "Yamen",
    "streetAddress": "81 Express Park",
    "stars": 5,
    "realty": "Hane and Sons",
    "shortRealtor": 'placeholder',
    "realtor": "Isadore Bunworth"
  }, {
    "id": 37,
    "squareFootage": 1409,
    "pricePerSquareFoot": 941,
    "rooms": 4,
    "beds": 1,
    "baths": 2,
    "houseType": "Rev",
    "neighborhood": "Hodošan",
    "streetAddress": "462 Oak Hill",
    "stars": 40,
    "realty": "Mann Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Izzy Delue"
  }, {
    "id": 38,
    "squareFootage": 1402,
    "pricePerSquareFoot": 1205,
    "rooms": 2,
    "beds": 1,
    "baths": 1,
    "houseType": "Mr",
    "neighborhood": "Hrib-Loški Potok",
    "streetAddress": "20 Longview Plaza",
    "stars": 50,
    "realty": "Dooley LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Prudy Ugolini"
  }, {
    "id": 39,
    "squareFootage": 861,
    "pricePerSquareFoot": 911,
    "rooms": 5,
    "beds": 2,
    "baths": 2,
    "houseType": "Dr",
    "neighborhood": "Bosilovo",
    "streetAddress": "1 Chinook Alley",
    "stars": 44,
    "realty": "Balistreri Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Sutherland Pedlow"
  }, {
    "id": 40,
    "squareFootage": 1399,
    "pricePerSquareFoot": 1063,
    "rooms": 6,
    "beds": 2,
    "baths": 1,
    "houseType": "Honorable",
    "neighborhood": "Versailles",
    "streetAddress": "639 Blackbird Circle",
    "stars": 40,
    "realty": "Watsica, Schmitt and Bins",
    "shortRealtor": 'placeholder',
    "realtor": "Baxie Kimblin"
  }, {
    "id": 41,
    "squareFootage": 758,
    "pricePerSquareFoot": 842,
    "rooms": 3,
    "beds": 2,
    "baths": 2,
    "houseType": "Ms",
    "neighborhood": "Hanfeng",
    "streetAddress": "915 Brickson Park Parkway",
    "stars": 20,
    "realty": "Spinka, Daugherty and Heller",
    "shortRealtor": 'placeholder',
    "realtor": "Elvis Balhatchet"
  }, {
    "id": 42,
    "squareFootage": 1340,
    "pricePerSquareFoot": 865,
    "rooms": 6,
    "beds": 2,
    "baths": 2,
    "houseType": "Honorable",
    "neighborhood": "Gulong",
    "streetAddress": "6 Nancy Street",
    "stars": 32,
    "realty": "Buckridge-Mueller",
    "shortRealtor": 'placeholder',
    "realtor": "Avivah Monkeman"
  }, {
    "id": 43,
    "squareFootage": 883,
    "pricePerSquareFoot": 1275,
    "rooms": 4,
    "beds": 2,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Huaiyuan Chengguanzhen",
    "streetAddress": "753 Forest Dale Way",
    "stars": 17,
    "realty": "Altenwerth-Hintz",
    "shortRealtor": 'placeholder',
    "realtor": "Lexie Kondratenya"
  }, {
    "id": 44,
    "squareFootage": 1338,
    "pricePerSquareFoot": 1190,
    "rooms": 5,
    "beds": 1,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Tapas",
    "streetAddress": "79986 Autumn Leaf Circle",
    "stars": 37,
    "realty": "Homenick-Heller",
    "shortRealtor": 'placeholder',
    "realtor": "Cletus Cowlard"
  }, {
    "id": 45,
    "squareFootage": 832,
    "pricePerSquareFoot": 1369,
    "rooms": 6,
    "beds": 2,
    "baths": 1,
    "houseType": "Dr",
    "neighborhood": "Caibiran",
    "streetAddress": "6506 Blue Bill Park Road",
    "stars": 20,
    "realty": "Cormier, Emard and Purdy",
    "shortRealtor": 'placeholder',
    "realtor": "Judd Nisuis"
  }, {
    "id": 46,
    "squareFootage": 1032,
    "pricePerSquareFoot": 1386,
    "rooms": 4,
    "beds": 1,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Rotunda",
    "streetAddress": "6 Jackson Crossing",
    "stars": 40,
    "realty": "Cruickshank-Osinski",
    "shortRealtor": 'placeholder',
    "realtor": "Kristos Eglinton"
  }, {
    "id": 47,
    "squareFootage": 1338,
    "pricePerSquareFoot": 1267,
    "rooms": 5,
    "beds": 2,
    "baths": 2,
    "houseType": "Honorable",
    "neighborhood": "Owase",
    "streetAddress": "1527 American Ash Avenue",
    "stars": 22,
    "realty": "Gusikowski LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Nickolas Adshed"
  }, {
    "id": 48,
    "squareFootage": 1153,
    "pricePerSquareFoot": 1405,
    "rooms": 5,
    "beds": 2,
    "baths": 2,
    "houseType": "Rev",
    "neighborhood": "Sarkanjut",
    "streetAddress": "111 Forest Dale Trail",
    "stars": 32,
    "realty": "Roob, Abshire and Schowalter",
    "shortRealtor": 'placeholder',
    "realtor": "Kerstin Votier"
  }, {
    "id": 49,
    "squareFootage": 1374,
    "pricePerSquareFoot": 1320,
    "rooms": 5,
    "beds": 2,
    "baths": 1,
    "houseType": "Rev",
    "neighborhood": "Velká Bystřice",
    "streetAddress": "04 Autumn Leaf Center",
    "stars": 6,
    "realty": "Mohr LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Kath Methingam"
  }, {
    "id": 50,
    "squareFootage": 1623,
    "pricePerSquareFoot": 1189,
    "rooms": 7,
    "beds": 3,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "El Congo",
    "streetAddress": "0 Sundown Parkway",
    "stars": 14,
    "realty": "Jones LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Aubrey O'Doohaine"
  }, {
    "id": 51,
    "squareFootage": 3602,
    "pricePerSquareFoot": 1042,
    "rooms": 5,
    "beds": 3,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "Bhola",
    "streetAddress": "6549 Hollow Ridge Street",
    "stars": 23,
    "realty": "Sanford Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Jeanie Gonzalo"
  }, {
    "id": 52,
    "squareFootage": 3567,
    "pricePerSquareFoot": 1188,
    "rooms": 7,
    "beds": 2,
    "baths": 4,
    "houseType": "Honorable",
    "neighborhood": "Svetlyy",
    "streetAddress": "82477 Towne Crossing",
    "stars": 45,
    "realty": "Cormier, Gerhold and Boehm",
    "shortRealtor": 'placeholder',
    "realtor": "Avie Ozintsev"
  }, {
    "id": 53,
    "squareFootage": 1788,
    "pricePerSquareFoot": 1326,
    "rooms": 5,
    "beds": 3,
    "baths": 4,
    "houseType": "Mrs",
    "neighborhood": "Yōkaichiba",
    "streetAddress": "014 Monterey Center",
    "stars": 49,
    "realty": "Kuphal LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Wallis Jose"
  }, {
    "id": 54,
    "squareFootage": 2480,
    "pricePerSquareFoot": 1184,
    "rooms": 7,
    "beds": 3,
    "baths": 2,
    "houseType": "Ms",
    "neighborhood": "Huaitu",
    "streetAddress": "8736 Hanson Road",
    "stars": 22,
    "realty": "Barrows and Sons",
    "shortRealtor": 'placeholder',
    "realtor": "Earvin Keward"
  }, {
    "id": 55,
    "squareFootage": 3536,
    "pricePerSquareFoot": 1412,
    "rooms": 7,
    "beds": 3,
    "baths": 5,
    "houseType": "Rev",
    "neighborhood": "Coayllo",
    "streetAddress": "03733 Carberry Circle",
    "stars": 3,
    "realty": "Altenwerth LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Fowler Stuehmeyer"
  }, {
    "id": 56,
    "squareFootage": 3735,
    "pricePerSquareFoot": 1136,
    "rooms": 5,
    "beds": 3,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "Maevatanana",
    "streetAddress": "9439 Myrtle Pass",
    "stars": 23,
    "realty": "Rodriguez, Schinner and Tremblay",
    "shortRealtor": 'placeholder',
    "realtor": "Yorker Hamshar"
  }, {
    "id": 57,
    "squareFootage": 2325,
    "pricePerSquareFoot": 1437,
    "rooms": 7,
    "beds": 3,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "Micheng",
    "streetAddress": "266 Hoepker Circle",
    "stars": 25,
    "realty": "Hills LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Josefina Danilchenko"
  }, {
    "id": 58,
    "squareFootage": 2392,
    "pricePerSquareFoot": 1467,
    "rooms": 8,
    "beds": 2,
    "baths": 4,
    "houseType": "Dr",
    "neighborhood": "Elói Mendes",
    "streetAddress": "751 Fisk Junction",
    "stars": 28,
    "realty": "Gaylord, Torp and Vandervort",
    "shortRealtor": 'placeholder',
    "realtor": "Rab MacMenamy"
  }, {
    "id": 59,
    "squareFootage": 1705,
    "pricePerSquareFoot": 1155,
    "rooms": 7,
    "beds": 4,
    "baths": 4,
    "houseType": "Ms",
    "neighborhood": "Gračanica",
    "streetAddress": "99 Arizona Point",
    "stars": 28,
    "realty": "Gibson, Kuhlman and O'Connell",
    "shortRealtor": 'placeholder',
    "realtor": "Boyd Giddins"
  }, {
    "id": 60,
    "squareFootage": 2285,
    "pricePerSquareFoot": 1044,
    "rooms": 6,
    "beds": 3,
    "baths": 5,
    "houseType": "Mrs",
    "neighborhood": "Şuraabad",
    "streetAddress": "0 Autumn Leaf Court",
    "stars": 43,
    "realty": "Veum-Gutkowski",
    "shortRealtor": 'placeholder',
    "realtor": "Correy Klazenga"
  }, {
    "id": 61,
    "squareFootage": 3267,
    "pricePerSquareFoot": 1476,
    "rooms": 5,
    "beds": 3,
    "baths": 3,
    "houseType": "Ms",
    "neighborhood": "Man",
    "streetAddress": "73 Briar Crest Court",
    "stars": 50,
    "realty": "Wyman, Graham and Miller",
    "shortRealtor": 'placeholder',
    "realtor": "Jenifer Frank"
  }, {
    "id": 62,
    "squareFootage": 1831,
    "pricePerSquareFoot": 1553,
    "rooms": 8,
    "beds": 4,
    "baths": 5,
    "houseType": "Honorable",
    "neighborhood": "Phong Điền",
    "streetAddress": "60154 West Place",
    "stars": 44,
    "realty": "Lueilwitz-Hermann",
    "shortRealtor": 'placeholder',
    "realtor": "Isac Emlen"
  }, {
    "id": 63,
    "squareFootage": 2989,
    "pricePerSquareFoot": 1397,
    "rooms": 7,
    "beds": 4,
    "baths": 2,
    "houseType": "Mr",
    "neighborhood": "Raemude",
    "streetAddress": "13 Surrey Parkway",
    "stars": 46,
    "realty": "Hermann, Kertzmann and Breitenberg",
    "shortRealtor": 'placeholder',
    "realtor": "Cozmo Duncklee"
  }, {
    "id": 64,
    "squareFootage": 2218,
    "pricePerSquareFoot": 1367,
    "rooms": 7,
    "beds": 4,
    "baths": 4,
    "houseType": "Mrs",
    "neighborhood": "Falköping",
    "streetAddress": "795 Dapin Trail",
    "stars": 27,
    "realty": "Waters, Kshlerin and Hessel",
    "shortRealtor": 'placeholder',
    "realtor": "Vallie Gieraths"
  }, {
    "id": 65,
    "squareFootage": 2007,
    "pricePerSquareFoot": 1325,
    "rooms": 8,
    "beds": 4,
    "baths": 4,
    "houseType": "Mr",
    "neighborhood": "Peterhof",
    "streetAddress": "118 International Way",
    "stars": 28,
    "realty": "Tremblay-Crooks",
    "shortRealtor": 'placeholder',
    "realtor": "Osbourne Gaiger"
  }, {
    "id": 66,
    "squareFootage": 1642,
    "pricePerSquareFoot": 1416,
    "rooms": 7,
    "beds": 2,
    "baths": 3,
    "houseType": "Rev",
    "neighborhood": "Shimiaozi",
    "streetAddress": "62579 Bashford Place",
    "stars": 4,
    "realty": "Rosenbaum LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Sandro Dooney"
  }, {
    "id": 67,
    "squareFootage": 3722,
    "pricePerSquareFoot": 1512,
    "rooms": 6,
    "beds": 4,
    "baths": 3,
    "houseType": "Honorable",
    "neighborhood": "Kishkenekol’",
    "streetAddress": "3 Aberg Circle",
    "stars": 24,
    "realty": "Mertz-Reichel",
    "shortRealtor": 'placeholder',
    "realtor": "Harrie Jendrusch"
  }, {
    "id": 68,
    "squareFootage": 1759,
    "pricePerSquareFoot": 1567,
    "rooms": 6,
    "beds": 4,
    "baths": 4,
    "houseType": "Ms",
    "neighborhood": "Busalangga",
    "streetAddress": "3 Stoughton Lane",
    "stars": 6,
    "realty": "Tromp-Johns",
    "shortRealtor": 'placeholder',
    "realtor": "Aime Pusey"
  }, {
    "id": 69,
    "squareFootage": 3796,
    "pricePerSquareFoot": 1086,
    "rooms": 8,
    "beds": 4,
    "baths": 3,
    "houseType": "Ms",
    "neighborhood": "Jardim do Seridó",
    "streetAddress": "3652 East Lane",
    "stars": 14,
    "realty": "Huels and Sons",
    "shortRealtor": 'placeholder',
    "realtor": "Antone Haggarty"
  }, {
    "id": 70,
    "squareFootage": 3135,
    "pricePerSquareFoot": 1239,
    "rooms": 5,
    "beds": 3,
    "baths": 4,
    "houseType": "Honorable",
    "neighborhood": "Minien East",
    "streetAddress": "58 Kennedy Park",
    "stars": 12,
    "realty": "Marvin, Conn and Goyette",
    "shortRealtor": 'placeholder',
    "realtor": "Edyth Fydoe"
  }, {
    "id": 71,
    "squareFootage": 2106,
    "pricePerSquareFoot": 1336,
    "rooms": 5,
    "beds": 3,
    "baths": 2,
    "houseType": "Dr",
    "neighborhood": "Zaječí",
    "streetAddress": "1 Eagle Crest Court",
    "stars": 41,
    "realty": "Fahey and Sons",
    "shortRealtor": 'placeholder',
    "realtor": "Lin Lanahan"
  }, {
    "id": 72,
    "squareFootage": 3118,
    "pricePerSquareFoot": 1204,
    "rooms": 6,
    "beds": 2,
    "baths": 4,
    "houseType": "Dr",
    "neighborhood": "‘Ayn al Bayḑā",
    "streetAddress": "14096 Mifflin Place",
    "stars": 25,
    "realty": "Schowalter, Mitchell and Rodriguez",
    "shortRealtor": 'placeholder',
    "realtor": "Edy Woodard"
  }, {
    "id": 73,
    "squareFootage": 1723,
    "pricePerSquareFoot": 1319,
    "rooms": 8,
    "beds": 4,
    "baths": 2,
    "houseType": "Honorable",
    "neighborhood": "Banjar Banyualit",
    "streetAddress": "86 Comanche Plaza",
    "stars": 34,
    "realty": "Rogahn LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Mavis Molan"
  }, {
    "id": 74,
    "squareFootage": 3467,
    "pricePerSquareFoot": 1254,
    "rooms": 6,
    "beds": 2,
    "baths": 3,
    "houseType": "Rev",
    "neighborhood": "Nouvelle France",
    "streetAddress": "7 Warner Street",
    "stars": 22,
    "realty": "Ondricka, Dare and Zemlak",
    "shortRealtor": 'placeholder',
    "realtor": "Madelin Beig"
  }, {
    "id": 75,
    "squareFootage": 5882,
    "pricePerSquareFoot": 1654,
    "rooms": 10,
    "beds": 4,
    "baths": 2,
    "houseType": "Honorable",
    "neighborhood": "Romanovskaya",
    "streetAddress": "3 Menomonie Pass",
    "stars": 26,
    "realty": "Mills and Sons",
    "shortRealtor": 'placeholder',
    "realtor": "Jackie Falshaw"
  }, {
    "id": 76,
    "squareFootage": 4469,
    "pricePerSquareFoot": 2964,
    "rooms": 11,
    "beds": 5,
    "baths": 3,
    "houseType": "Mr",
    "neighborhood": "Kristianstad",
    "streetAddress": "98286 Bowman Court",
    "stars": 8,
    "realty": "O'Keefe, Miller and Miller",
    "shortRealtor": 'placeholder',
    "realtor": "Ham Naisbit"
  }, {
    "id": 77,
    "squareFootage": 6648,
    "pricePerSquareFoot": 2475,
    "rooms": 8,
    "beds": 6,
    "baths": 3,
    "houseType": "Mrs",
    "neighborhood": "Buenos Aires",
    "streetAddress": "9 Pearson Junction",
    "stars": 6,
    "realty": "Runolfsdottir-Johns",
    "shortRealtor": 'placeholder',
    "realtor": "Dugald Friary"
  }, {
    "id": 78,
    "squareFootage": 6638,
    "pricePerSquareFoot": 2520,
    "rooms": 12,
    "beds": 5,
    "baths": 2,
    "houseType": "Ms",
    "neighborhood": "Dolní Černilov",
    "streetAddress": "885 Lighthouse Bay Junction",
    "stars": 12,
    "realty": "Crist Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Paulie Skedgell"
  }, {
    "id": 79,
    "squareFootage": 4468,
    "pricePerSquareFoot": 2196,
    "rooms": 8,
    "beds": 7,
    "baths": 4,
    "houseType": "Honorable",
    "neighborhood": "Jendouba",
    "streetAddress": "09 Kingsford Trail",
    "stars": 7,
    "realty": "Glover Group",
    "shortRealtor": 'placeholder',
    "realtor": "Konstantine Rupert"
  }, {
    "id": 80,
    "squareFootage": 4819,
    "pricePerSquareFoot": 1601,
    "rooms": 11,
    "beds": 7,
    "baths": 5,
    "houseType": "Honorable",
    "neighborhood": "Montijo",
    "streetAddress": "22 Northfield Court",
    "stars": 4,
    "realty": "Wilkinson-Nikolaus",
    "shortRealtor": 'placeholder',
    "realtor": "Jackson Althrop"
  }, {
    "id": 81,
    "squareFootage": 4409,
    "pricePerSquareFoot": 2506,
    "rooms": 8,
    "beds": 7,
    "baths": 4,
    "houseType": "Mrs",
    "neighborhood": "Zhihe",
    "streetAddress": "6514 Alpine Hill",
    "stars": 40,
    "realty": "Pfannerstill Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Carry Duthie"
  }, {
    "id": 82,
    "squareFootage": 4037,
    "pricePerSquareFoot": 2787,
    "rooms": 10,
    "beds": 3,
    "baths": 2,
    "houseType": "Mr",
    "neighborhood": "Planken",
    "streetAddress": "9 Norway Maple Circle",
    "stars": 36,
    "realty": "Wisoky, Kerluke and Reichert",
    "shortRealtor": 'placeholder',
    "realtor": "Hersh Wein"
  }, {
    "id": 83,
    "squareFootage": 6258,
    "pricePerSquareFoot": 2146,
    "rooms": 12,
    "beds": 6,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "Massy",
    "streetAddress": "86 Mallory Pass",
    "stars": 26,
    "realty": "Cormier, Gutmann and Steuber",
    "shortRealtor": 'placeholder',
    "realtor": "Ericha Redington"
  }, {
    "id": 84,
    "squareFootage": 6396,
    "pricePerSquareFoot": 1841,
    "rooms": 9,
    "beds": 5,
    "baths": 5,
    "houseType": "Rev",
    "neighborhood": "Butere",
    "streetAddress": "47 Milwaukee Terrace",
    "stars": 20,
    "realty": "Kohler-Dickinson",
    "shortRealtor": 'placeholder',
    "realtor": "Sandi Alvis"
  }, {
    "id": 85,
    "squareFootage": 3004,
    "pricePerSquareFoot": 2032,
    "rooms": 9,
    "beds": 3,
    "baths": 5,
    "houseType": "Mrs",
    "neighborhood": "Bell Ville",
    "streetAddress": "4166 International Street",
    "stars": 19,
    "realty": "Tremblay, O'Keefe and Wisoky",
    "shortRealtor": 'placeholder',
    "realtor": "Olav Gayler"
  }, {
    "id": 86,
    "squareFootage": 6139,
    "pricePerSquareFoot": 2990,
    "rooms": 12,
    "beds": 5,
    "baths": 5,
    "houseType": "Honorable",
    "neighborhood": "Kimje",
    "streetAddress": "49 Bunting Crossing",
    "stars": 45,
    "realty": "Hettinger Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Roz Mohammad"
  }, {
    "id": 87,
    "squareFootage": 4983,
    "pricePerSquareFoot": 1959,
    "rooms": 12,
    "beds": 4,
    "baths": 4,
    "houseType": "Mrs",
    "neighborhood": "Aguas Corrientes",
    "streetAddress": "40 Monument Pass",
    "stars": 35,
    "realty": "Rau Group",
    "shortRealtor": 'placeholder',
    "realtor": "Cherlyn Gasperi"
  }, {
    "id": 88,
    "squareFootage": 6174,
    "pricePerSquareFoot": 2526,
    "rooms": 9,
    "beds": 5,
    "baths": 4,
    "houseType": "Honorable",
    "neighborhood": "Longmiao",
    "streetAddress": "793 Caliangt Park",
    "stars": 17,
    "realty": "Toy-Herman",
    "shortRealtor": 'placeholder',
    "realtor": "Gerianna Dobrowski"
  }, {
    "id": 89,
    "squareFootage": 5112,
    "pricePerSquareFoot": 1822,
    "rooms": 12,
    "beds": 5,
    "baths": 5,
    "houseType": "Honorable",
    "neighborhood": "Ujsoły",
    "streetAddress": "5568 Express Drive",
    "stars": 30,
    "realty": "Rau LLC",
    "shortRealtor": 'placeholder',
    "realtor": "Lori Jiroutka"
  }, {
    "id": 90,
    "squareFootage": 3978,
    "pricePerSquareFoot": 1909,
    "rooms": 12,
    "beds": 5,
    "baths": 5,
    "houseType": "Dr",
    "neighborhood": "Drien Rampak",
    "streetAddress": "1 Bay Park",
    "stars": 14,
    "realty": "Cartwright Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Kerstin Lamball"
  }, {
    "id": 91,
    "squareFootage": 4929,
    "pricePerSquareFoot": 2604,
    "rooms": 9,
    "beds": 5,
    "baths": 4,
    "houseType": "Mr",
    "neighborhood": "Pordapor Barat",
    "streetAddress": "8 Melrose Junction",
    "stars": 28,
    "realty": "Lueilwitz-Barton",
    "shortRealtor": 'placeholder',
    "realtor": "Korella Suttling"
  }, {
    "id": 92,
    "squareFootage": 3252,
    "pricePerSquareFoot": 1931,
    "rooms": 12,
    "beds": 7,
    "baths": 5,
    "houseType": "Dr",
    "neighborhood": "Ershilipu",
    "streetAddress": "7 Almo Trail",
    "stars": 29,
    "realty": "Quitzon, Stracke and Turcotte",
    "shortRealtor": 'placeholder',
    "realtor": "Markus Sivewright"
  }, {
    "id": 93,
    "squareFootage": 4260,
    "pricePerSquareFoot": 2037,
    "rooms": 8,
    "beds": 4,
    "baths": 5,
    "houseType": "Ms",
    "neighborhood": "Huanchillas",
    "streetAddress": "5 Holy Cross Center",
    "stars": 10,
    "realty": "Spencer Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Nady Housegoe"
  }, {
    "id": 94,
    "squareFootage": 4890,
    "pricePerSquareFoot": 2519,
    "rooms": 10,
    "beds": 4,
    "baths": 3,
    "houseType": "Rev",
    "neighborhood": "Uherský Ostroh",
    "streetAddress": "97168 Spohn Crossing",
    "stars": 26,
    "realty": "Mante, Schinner and Haley",
    "shortRealtor": 'placeholder',
    "realtor": "Lurette MacCard"
  }, {
    "id": 95,
    "squareFootage": 3379,
    "pricePerSquareFoot": 2572,
    "rooms": 12,
    "beds": 6,
    "baths": 2,
    "houseType": "Dr",
    "neighborhood": "Vacenovice",
    "streetAddress": "419 Hermina Lane",
    "stars": 8,
    "realty": "McLaughlin, Parker and Zulauf",
    "shortRealtor": 'placeholder',
    "realtor": "Seka Maffy"
  }, {
    "id": 96,
    "squareFootage": 6542,
    "pricePerSquareFoot": 2485,
    "rooms": 9,
    "beds": 3,
    "baths": 5,
    "houseType": "Mr",
    "neighborhood": "Vancouver",
    "streetAddress": "4 6th Pass",
    "stars": 24,
    "realty": "Harber-Barton",
    "shortRealtor": 'placeholder',
    "realtor": "Ezri Polland"
  }, {
    "id": 97,
    "squareFootage": 5991,
    "pricePerSquareFoot": 2399,
    "rooms": 9,
    "beds": 5,
    "baths": 5,
    "houseType": "Rev",
    "neighborhood": "Promyshlennovskiy",
    "streetAddress": "51404 Chive Drive",
    "stars": 7,
    "realty": "Pollich, Murphy and Paucek",
    "shortRealtor": 'placeholder',
    "realtor": "Hillery Kebbell"
  }, {
    "id": 98,
    "squareFootage": 6436,
    "pricePerSquareFoot": 1799,
    "rooms": 9,
    "beds": 3,
    "baths": 5,
    "houseType": "Mr",
    "neighborhood": "Twardogóra",
    "streetAddress": "624 Hazelcrest Circle",
    "stars": 3,
    "realty": "Moore-Dicki",
    "shortRealtor": 'placeholder',
    "realtor": "Had Kintzel"
  }, {
    "id": 99,
    "squareFootage": 4957,
    "pricePerSquareFoot": 2631,
    "rooms": 8,
    "beds": 6,
    "baths": 4,
    "houseType": "Honorable",
    "neighborhood": "Michałowice",
    "streetAddress": "5109 Union Circle",
    "stars": 3,
    "realty": "Denesik Inc",
    "shortRealtor": 'placeholder',
    "realtor": "Juliane Hartop"
  }, {
    "id": 100,
    "squareFootage": 3264,
    "pricePerSquareFoot": 2941,
    "rooms": 12,
    "beds": 6,
    "baths": 4,
    "houseType": "Dr",
    "neighborhood": "Kablukan",
    "streetAddress": "8 Russell Lane",
    "stars": 48,
    "realty": "Fisher-Rippin",
    "shortRealtor": 'placeholder',
    "realtor": "Babbie Smythin"
  }
];

module.exports.myData = myData;